#!/usr/bin/env ruby

current_branch = `git symbolic-ref HEAD`.chomp.split('/').last
reviewme_server_url = `git config reviewme.server.url`.chomp
publisher_email = `git config user.email`.chomp
publisher_name = `git config user.name`.chomp

number_of_commits = (ARGV[0] || 1).to_i

commit_shorthashes = %x[git log -#{number_of_commits} --pretty=format:'%h'].split("\n")
commit_emails = %x[git log -#{number_of_commits} --pretty=format:'%ce'].split("\n")
commit_messages = %x[git log -#{number_of_commits} --pretty=format:'%s'].split("\n")
commit_dates = %x[git log -#{number_of_commits} --pretty=format:'%ci'].split("\n")

post_query = "review[publisher_email]=#{publisher_email}&review[publisher_name]=#{publisher_name}&review[branch]=#{current_branch}"

number_of_commits.times { |i|
  post_query << "&commit[][shorthash]=#{commit_shorthashes[i]}"
  post_query << "&commit[][message]=#{commit_messages[i]}"
  post_query << "&commit[][email]=#{commit_emails[i]}"
  post_query << "&commit[][date]=#{commit_dates[i]}"  
}

exec("curl -d '" << post_query << "' #{reviewme_server_url}")